const LogIcons = {
    CheckMark: "✓",
    CrossMark: "✗",
    InformationSource: "ℹ",
    Sparkles: "✨",
    BlackUpPointingTriangle: "▲",
    BlackDownPointingTriangle: "▼",
    WhiteUpPointingTriangle: "△",
    WhiteDownPointingTriangle: "▽",
    Ellipsis: "…",
    ArrowRight: "→",
    ArrowLeft: "←",
    ArrowUp: "↑",
    ArrowDown: "↓",
    TwoHeadedArrowRight: "⇄",
    TwoHeadedArrowLeft: "⇆",
    TwoHeadedArrowUp: "⇅",
    TwoHeadedArrowDown: "⇇",
    HookLeftArrow: "↩",
    HookRightArrow: "↪",
    LeftwardsArrowWithHook: "↩",
    RightwardsArrowWithHook: "↪",
    UpwardsArrowWithHook: "↰",
    DownwardsArrowWithHook: "↲",
    CircleArrowRight: "↻",
    CircleArrowLeft: "↺",
    Therefore: "∴",
    Because: "∵",
}

export default LogIcons